services:
  - type: web
    name: whispr-chat
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    env: production
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production